$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
language: en-GB
allowCompoundWords: true
import:
  - '@cspell/dict-de-de/cspell-ext.json'
  - '@cspell/dict-ru_ru/cspell-ext.json'
dictionaries:
  - bash
  - companies
  - dart
  - en-GB
  - en_US
  - filetypes
  - flutter
  - fonts
  - markdown
  - misc
  - powershell
  - rust
  - softwareTerms
flagWords:
  - hte
words:
  - Accessibility
  - cdylib
  - Cred
  - desugar
  - documentsui
  - EWOULDBLOCK
  - fcntl
  - fvmrc
  - Gitea
  - GITEA
  - GitSync
  - hardis
  - Izzy
  - msgnum
  - Nodelete
  - oids
  - osascript
  - osshkeys
  - pbxproj
  - sdcard
  - unpulled
  - unpushed
  - vendored
  - venv
  - webp
  - wline
  - xcodeproj
  - xcworkspace
  - xxxhdpi
ignoreWords:
  - analyzer
  - analyzes
  - anys
  - behavior
  - DARTANALYZER
  - defenses
  - dialog
  - Dialogs
  - efgh
  - favor
  - kinded
  - KTLINT
  - lineageos
  - linters
  - notif
  - obsi
  - Recents
  - Repro
  - specfic
  - stls
  - vars
  - xcassets
  - youre
ignorePaths:
  - .cspell.json
  - .gitignore
  - .jscpd.json
  - notes.md
  - rust_builder/cargokit/**
  - task_plan.md
  - .git/**
  - .github/**
  - .vite/**
  - node_modules/**
  - .vscode/**
  - dist/**
  - .mega-linter/**
  - megalinter-reports/**
overrides:
  - filename: 'fastlane/metadata/android/de/**'
    language: de-DE
    dictionaries:
      - de-de
    words:
      - Barrierefreiheitsdienstes
  - filename: 'fastlane/metadata/android/ru/**'
    language: ru
    dictionaries:
      - ru-ru
    words:
      - коммита
